# Site settings
title: gsyx
SEOTitle: 盖世英雄的技术博客
header-img: img/post-bg-desk.jpg
email: gsyx@gmail.com
description: "盖世英雄, gsyx666, Android博客, Android源码"
keyword: "盖世英雄, gsyx666, Android博客, Android源码"
url:  https://gsyx.vercel.app/ #"https://gsyx666.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    gsyx666
#twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["bak","less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
#disqus_username: hux

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: 1b2ebc33bdcea356ba836517ea1090d8

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "gsyx，编程语言初心者"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "邱柏荧",
        href: "http://qiubaiying.vip"
    },{
        title: "尼古拉斯.赵四",
        href: "http://www.wjdiankong.cn"
    },{
        title: "廖雪峰",
        href: "https://www.liaoxuefeng.com/"
    },{
        title: "Android",
        href: "https://developer.android.google.cn/"
    },{ 
        title: "Java",
        href: "https://snailclimb.gitee.io/javaguide-interview"
    },{
        title: "源码在线阅读",
        href: "http://www.coderead.cn/"
    },{
        title: "JavaGuide",
        href: "https://snailclimb.gitee.io/javaguide/"
    },{
        title: "阿里java开发手册",
        href: "https://developer.aliyun.com/special/tech-java"
    },{
        title: "中文技术文档的写作规范",
        href: "https://github.com/ruanyf/document-style-guide"
    },{
        title: "make-money",
        href: "https://github.com/easychen/howto-make-more-money"
    },{
        title: "Indie Hackers",
        href: "https://indiehacker.im/"
    },{
        title: "linux-0.12",
        href: "http://www.oldlinux.org/Book-Lite/" # PDF：http://www.oldlinux.org/download/CLK-5.0.1-WithCover.pdf
    },{
        title: "Jianwu Gao",
        href: "https://www.androidperformance.com/2019/12/01/BlogMap/"
    },{
        title: "wanandroid nav",
        href: "https://www.wanandroid.com/navi"
    },{
        title: "有关 git 的学习资料",
        href: "https://github.com/xirong/my-git"
    }
    
]
